export const CELL_HEIGHT_PX = 15;
export const CELL_WEIGHT_PX = 15;

export const CELLS_HORIZONTAL_COUNT = 15;
export const CELLS_VERTICAL_COUNT = 15;

export const TABLE_HEIGHT_PX = CELLS_VERTICAL_COUNT * CELL_HEIGHT_PX;
export const TABLE_WIDTH_PX = CELLS_HORIZONTAL_COUNT * CELL_WEIGHT_PX;

export const PLATFORM_WIDHT_CELLS_COUNT = 3;

